# SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

sonar.projectKey=carbonio-configd
sonar.projectName=carbonio-configd
sonar.exclusions=**/*_test.go,test/**
sonar.test.inclusions=**/*_test.go
sonar.go.golangci-lint.reportPaths=linter.out
sonar.go.coverage.reportPaths=coverage.out
